### PR TITLE
Fix: bump `mytoyota` to 2.1.0 and fix `shopGenuinePartsUrl` validation

### PR DESCRIPTION
**Pull request by CM000n**
Fix: https://github.com/DurgNomis-drol/ha_toyota/issues/236

### CODE REVIEW

**Comment by CM000n** [comment]
Hi, @DurgNomis-drol, can you please take a look and approve if the changes are ok for you. 😊 
Thank you

**Comment by flynnjonsson** [comment]
Any one know when this will be solved in a new updated version? Thanks!

**Comment by CM000n** [comment]
> Any one know when this will be solved in a new updated version? Thanks!

I just waiting for an approval from @DurgNomis-drol

**Comment by ajain-93** [comment]
See https://github.com/DurgNomis-drol/ha_toyota/issues/236#issuecomment-1946248244 for a fix if you are impatient like me.

**Review by DurgNomis-drol — APPROVED** [review]

**Pull request merged**
