### PR TITLE
Spanish language

### PR DESCRIPTION
**Pull request by renewoensdregt**
Added Spanish language translation

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
Please rename the language file to `es.json` 😃

**Comment by renewoensdregt** [comment]
I didn´t even add the file yet... first created the PR now I will add.

**Comment by DurgNomis-drol** [comment]
You need to make a new branch every time you want to make a new PR or it will mess up the commit history. Also please update your branch again so that it is up to date. 😃

**Comment by renewoensdregt** [comment]
OK so I think I did it right with the Dutch one. Should I delete this one and start over?

**Comment by DurgNomis-drol** [comment]
I fixed this one, but yes in the future open a new branch for each PR or update your fork between each PR merged so you always have the latest.

**Review by DurgNomis-drol — APPROVED** [review]

**Pull request merged**
