### PR TITLE
Catalan language added

### PR DESCRIPTION
**Pull request by renewoensdregt**
Added catalan language translation file

### CODE REVIEW

**Comment by DurgNomis-drol** [comment]
I am not language expert, how much difference is there between the Spanish and Catalan?

**Comment by renewoensdregt** [comment]
Enough that Spanish people don’t understand it and I assure you that Catalans really appreciate if their language is represented 😁

**Comment by DurgNomis-drol** [comment]
Right, glad you could clarify it. 😄 

The filename should be `ca.json` and not ``ct.json` as `ca` is the language-code  for Catalunya 😃 But you did a great job and I appreciate you contribution a lot. 

I haven't been able to find a list over which language are the correct ones beside checking what another integration i have been involved with.

**Comment by renewoensdregt** [comment]
OK. Renamed the file.

**Review by DurgNomis-drol — APPROVED** [review]
Thanks!

**Pull request merged**
